version: '3'
services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/your-database-name  # MongoDB 연결 정보
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
